name: Contexts
on: push
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Contexts
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Event: ${{ github.event_name }}"
          echo "OS: ${{ runner.os }}"
