name: Release Workflow
on: push
jobs:
  release:
    uses: ./.github/workflows/notify.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      NOTIFY_TOKEN: ${{ github.event.inputs.NOTIFY_TOKEN }}
