name: secrets
on: push
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Call the API
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          if [ -n "$APP_TOKEN" ]; then
            echo "token is available to this step"
          fi
                                                  
